name: libnvme meson CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  meson-build:
    runs-on: ubuntu-latest

    steps:
      - name: install libraries
        run: sudo apt-get install libjson-c-dev
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
