---
name: libnvme muon

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-minimal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build muon
        run: |
          mkdir build-tools
          cd build-tools
          git clone --depth 1 https://git.sr.ht/~lattis/muon
          cd muon

          export CC=gcc
          export ninja=build/samu

          ./tools/bootstrap_ninja.sh build
          ./bootstrap.sh build

          build/muon setup -Dlibcurl=disabled -Dlibarchive=disabled -Ddocs=disabled -Dsamurai=disabled build
          build/samu -C build
          build/muon -C build test

      - name: build libnvme
        run: |
          export PATH=$(pwd)/build-tools/muon/build:$PATH

          muon setup -Dprefix=/tmp/nvme-cli-muon -Dpython=false -Dopenssl=disabled -Dlibdbus=disabled -Djson-c=disabled build-libnvme
          samu -C build-libnvme
